---
title: "Final Porject Proposal"
author: Yuqi Wang; Rongqing Jia; Xiaoyu Li; Yan Song
output: github_document
---

**The group members**

We have four people in our group:

* Yuqi Wang (yw3436)
* Rongqing Jia (rj2579)
* Xiaoyu Li (xl2834)
* Yan Song (ys3295)

**The tentative project title**

Trend of HIV diagnosis in NYC and the distribution of condom availability program locations


**The motivation for this project**

We are curious about the trend of HIV diagnosis in NYC from 2010 to 2017, and whether the condom availability program in 2018 satisfy the need of condoms in boroughs with high HIV incidences.

**The intended final products**

* We intend to create a webpage containing an overview of the project scope, data, approaches, visualizations, and full report. We plan to contain a dashboard in our webpage.

**The anticipated data sources**

We used data from the following datasets in NYC OpenData:

*HIV/AIDS Diagnoses by Neighborhood, Sex, and Race/Ethnicity*

These data were reported to the NYC DOHMH by June 30, 2014

This dataset includes data on new diagnoses of HIV and AIDS in NYC for the calendar years 2010 through 2013. Reported cases and case rates (per 100,000 population) are stratified by age group, race/ethnicity, and United Hospital Fund (UHF) neighborhood. For more information, please visit the HIV/AIDS Surveillance Data module on EpiQuery: nyc.gov/health/epiquery

*HIV Testing Locations*

Location and facility information for places in New York City that provide HIV testing.

*HIV/AIDS Annual Surveillance Statistics*

Annual data are provided on new diagnoses of HIV (non-AIDS), concurrent HIV/AIDS and AIDS, as well as the number of persons living with HIV and AIDS and the number of deaths among persons with HIV and AIDS. The data are shown for New York City overall and by sex, race, age, borough, area-based poverty level, risk factor, and United Hospital Fund neighborhood.

**The planned analyses / visualizations / coding challenges**

**The planned timeline**




